# Generated by Django 3.1.1 on 2020-09-18 16:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('time', models.DateTimeField(default=datetime.datetime.now, help_text='Time at which reading was taken (date-time)', primary_key=True, serialize=False)),
                ('firstNum', models.FloatField()),
                ('secondNum', models.FloatField()),
                ('thirdNum', models.FloatField()),
                ('fourthNum', models.FloatField()),
                ('fifthNum', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
