# Generated by Django 3.1.1 on 2020-09-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='z',
        ),
    ]
