# Generated by Django 3.1.1 on 2020-11-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_remove_settings_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
