# Generated by Django 3.1.1 on 2020-11-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_auto_20201129_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='picture',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
    ]
