# Generated by Django 3.1.5 on 2021-04-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0008_auto_20210321_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='meter_type',
            field=models.IntegerField(choices=[(0, 'Analog'), (1, 'Digital')], default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='w',
            field=models.IntegerField(default=0),
        ),
    ]
